[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish  = ".next"
  functions = "netlify/functions"   # ensure Netlify uses your functions dir

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "10.16.1"
  NETLIFY_BUILD_DEBUG = "true"

# Next.js adapter (must be present for Next 14 on Netlify)
[[plugins]]
  package = "@netlify/plugin-nextjs"


[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# CORS per environment (optional; your API should also enforce)
[context.production.environment]
  CORS_ALLOWED_ORIGINS = "https://cethos.com,https://*.cethos.com,https://*.vercel.app"

[context.deploy-preview.environment]
  CORS_ALLOWED_ORIGINS = "*"

[context.branch-deploy.environment]
  CORS_ALLOWED_ORIGINS = "*"
