[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish  = ".next"
  node_version = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# (Optional but nice)
[context.production.environment]
  CORS_ALLOWED_ORIGINS = "*"

[context.deploy-preview.environment]
  CORS_ALLOWED_ORIGINS = "*"

[context.branch-deploy.environment]
  CORS_ALLOWED_ORIGINS = "*"


[[plugins]]
package = "netlify-plugin-inngest"

  [plugins.inputs]
    host = "https://cethosv3.netlify.app"
    path = "/api/inngest"
