[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish  = ".next"

[build.environment]
  NODE_VERSION = "20"

# Next.js adapter
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Inngest build plugin — auto-registers your /api/inngest endpoint
[[plugins]]
  package = "netlify-plugin-inngest"
  [plugins.inputs]
    # Don't hardcode host; Netlify sets it per deploy (prod & previews).
    path = "/api/inngest"

[functions]
  node_bundler = "esbuild"

# CORS per environment (optional; your API should also enforce)
[context.production.environment]
  CORS_ALLOWED_ORIGINS = "https://cethos.com,https://*.cethos.com,https://*.vercel.app"

[context.deploy-preview.environment]
  CORS_ALLOWED_ORIGINS = "*"

[context.branch-deploy.environment]
  CORS_ALLOWED_ORIGINS = "*"