[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish  = ".next"
  node_version = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# CORS per environment (optional; your API should also handle CORS)
[context.production.environment]
  CORS_ALLOWED_ORIGINS = "https://cethos.com,https://*.cethos.com,https://*.vercel.app"

[context.deploy-preview.environment]
  CORS_ALLOWED_ORIGINS = "*"

[context.branch-deploy.environment]
  CORS_ALLOWED_ORIGINS = "*"

[[plugins]]
package = "netlify-plugin-inngest"
  [plugins.inputs]
    host = "https://cethosv3.netlify.app"
    path = "/.netlify/functions/inngest"