[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish  = ".next"
  node_version = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
