[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
included_files = ["gcs-cors-*.json"]

[[plugins]]
package = "netlify-plugin-inngest"
  [plugins.inputs]
  # Path to your Inngest handler as a Netlify Function
  path = "/.netlify/functions/inngest"

# Optional convenience: keep /api/inngest working
[[redirects]]
from = "/api/inngest"
to = "/.netlify/functions/inngest"
status = 200
